### ISSUE TITLE
add SQL commands

### ISSUE THREAD

**Issue by huangjinsuzhou** [aaronwangy/Data-Science-Cheatsheet#2]

**Comment by aaronwangy** [comment]
Please refer to the README:

**_Why is Python/SQL not covered in this cheatsheet?_**
This resource covers mainly algorithms, models, and concepts, as these rarely change and are common throughout industries. Technical languages and data structures often vary by job function, and refreshing these skills may make more sense on keyboard than on paper.
Additionally, there are plenty of existing resources online that cover SQL.
