### ISSUE TITLE
Additional topics

### ISSUE THREAD

**Issue by dbalabka** [aaronwangy/Data-Science-Cheatsheet#5]
Here is a list of topics that would be great to add:
1. Graph Neural Networks.
2. Bayesian Statistics, Probabilistic programming and application for A/B testing.
3. DBSCAN in the Clustering section.
4. SVD, Factorization Machines, and Neural Network approaches in RecSys section
5. Deep Reinforcement learning

**Comment by aaronwangy** [comment]
Thanks for the ideas! I will add them to the to-do list
